{{- if not .Values.providers.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora.fullname" . }}-providers
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- include "aurora.providerSecretData" . | nindent 2 }}
  {{- if or .Values.redis.enabled .Values.cache.redis.url }}
  REDIS_URL: {{ include "aurora.redisUrl" . | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.auth.masterKey (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora.fullname" . }}-auth
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ .Values.auth.masterKey | quote }}
{{- end }}
