package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func runInitSubcommand(args []string, stdout, stderr io.Writer) (handled bool, exitCode int) {
	if len(args) < 1 || args[0] != "init" {
		return false, 0
	}

	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", ".", "Target directory to initialize")
	force := fs.Bool("force", false, "Overwrite existing files")
	withModels := fs.Bool("with-models", false, "Also download model registry")
	if err := fs.Parse(args[1:]); err != nil {
		return true, 2
	}

	return true, initProject(*dir, *force, *withModels, stdout, stderr)
}

func initProject(dir string, force, withModels bool, stdout, stderr io.Writer) int {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		fmt.Fprintf(stderr, "error: failed to resolve path: %v\n", err)
		return 1
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		fmt.Fprintf(stderr, "error: failed to create directory %s: %v\n", dir, err)
		return 1
	}

	origDir, _ := os.Getwd()
	if err := os.Chdir(dir); err != nil {
		fmt.Fprintf(stderr, "error: failed to enter directory %s: %v\n", dir, err)
		return 1
	}
	defer func() { _ = os.Chdir(origDir) }()

	type fileSpec struct {
		path    string
		content string
		label   string
	}

	files := []fileSpec{
		{"config.yaml", initConfigYAML, "config.yaml"},
		{".env", initEnvTemplate, ".env"},
	}
	stubs := []fileSpec{
		{"data/user_pricing.yaml", initPricingStub, "data/user_pricing.yaml"},
		{"configs/fallback.json", initFallbackStub, "configs/fallback.json"},
	}

	for _, f := range files {
		if _, err := os.Stat(f.path); err == nil && !force {
			fmt.Fprintf(stderr, "error: %s already exists (use -force to overwrite)\n", f.path)
			return 1
		}
		if err := os.WriteFile(f.path, []byte(f.content), 0644); err != nil {
			fmt.Fprintf(stderr, "error: failed to write %s: %v\n", f.path, err)
			return 1
		}
		fmt.Fprintf(stdout, "  created  %s\n", f.label)
	}

	for _, f := range stubs {
		if err := os.MkdirAll(filepath.Dir(f.path), 0755); err != nil {
			continue
		}
		if _, err := os.Stat(f.path); os.IsNotExist(err) {
			_ = os.WriteFile(f.path, []byte(f.content), 0644)
			fmt.Fprintf(stdout, "  created  %s\n", f.label)
		}
	}

	fmt.Fprintf(stdout, "\n  Aurora gateway initialized in %s\n", absDir)

	if withModels {
		fmt.Fprintf(stdout, "\n  Downloading model registry...\n")
		if code := modelsSyncCmd(nil, stdout, stderr); code != 0 {
			fmt.Fprintf(stdout, "  (skip models sync — run 'aurora models sync' later)\n")
		}
	}

	fmt.Fprintf(stdout, "\n  Next steps:\n")
	fmt.Fprintf(stdout, "    1. Edit .env with your API keys\n")
	fmt.Fprintf(stdout, "    2. (Optional) aurora models sync\n")
	fmt.Fprintf(stdout, "    3. Run: aurora\n")
	return 0
}

const initConfigYAML = `# ═══════════════════════════════════════════════════════════════════════════
# Aurora Gateway — Configuration
# Generated by aurora init
# ═══════════════════════════════════════════════════════════════════════════
#
# Config pipeline:  code defaults -> this YAML -> env vars (env vars win).
# Keep secrets (API keys, database passwords) in .env, not in this file.
# To enable a commented option, uncomment it and adjust the value.
#
# Quick reference of available sections:
#   server          HTTP port, base path, passthrough routes, auth
#   admin           Admin API and dashboard UI
#   models          Model discovery, overrides, allowlisting
#   storage         SQLite (default), PostgreSQL, or MongoDB
#   logging         Audit logging of requests/responses
#   usage           Token usage tracking and retention
#   metrics         Prometheus /metrics endpoint
#   guardrails      Content guardrails and safety filters
#   cache           Model cache, Redis response cache, semantic cache
#   combos          Multi-model combo calls
#   cli_tools       CLI tool integration
#   token_saver     Output compression / token-saving transforms
#   fallback        Fallback routing rules
#   resilience      Retry logic and circuit breaker
#   providers       Explicit provider definitions (optional)
#   pools           Provider load-balancing pools
#   workflows       Workflow refresh cadence
# ═══════════════════════════════════════════════════════════════════════════

edition:
  name: oss

# ── Server ──────────────────────────────────────────────────────────────
# Controls the HTTP listener, URL routing, and security master key.
server:
  # HTTP port the gateway listens on.  (default: "8080")
  port: "8080"

  # URL path prefix for mounting behind a reverse proxy. (default: "/")
  base_path: "/"

  # Master key for admin API and gateway auth. References the env var.
  # CHANGE THIS before exposing outside localhost.  (default: "")
  master_key: "${AURORA_MASTER_KEY}"

  # When true, exposes /p/{provider}/... pass-through routes so clients can
  # call provider-native APIs directly through the gateway.  (default: true)
  enable_passthrough_routes: true

  # When true, allows both /p/{provider}/v1/... and /p/{provider}/... paths
  # for pass-through routes.  (default: true)
  allow_passthrough_v1_alias: true

  # Comma-separated provider types enabled for pass-through. Only these
  # providers get /p/{provider}/... routes.  (default: openai,anthropic,...)
  enabled_passthrough_providers: ["openai", "anthropic", "openrouter", "zai", "vllm"]

  # Expose /v1/messages for native Anthropic-format clients directly
  # alongside the OpenAI-compatible /v1/chat/completions.
  enable_anthropic_ingress: true

  # Maximum request body size. Accepts values like "10M", "1G", "500K".
  # (default: "10M")
  body_size_limit: 10M

  # Expose Swagger UI at /swagger/index.html
  swagger_enabled: true

  # Expose pprof profiling routes at /debug/pprof/*
  pprof_enabled: true

# ── Admin API & Dashboard ───────────────────────────────────────────────
# Built-in admin UI for managing providers, models, API keys, and settings.
admin:
  # Enable /admin/api/v1/* REST endpoints  (default: true)
  endpoints_enabled: true

  # Enable the admin web dashboard at /admin/dashboard  (default: true)
  ui_enabled: true

  # Dashboard UI at /admin/dashboard

# ── Model Discovery ─────────────────────────────────────────────────────
# Controls how models are discovered, enabled, and exposed via the API.
models:
  # Default availability for provider models when no override exists.
  # Set to false to require explicit enabling of each model.  (default: true)
  enabled_by_default: true

  # Allow per-model enable/disable overrides via the admin dashboard or
  # the user_pricing.yaml file.  (default: true)
  overrides_enabled: true

  # When true, GET /v1/models returns only enabled model aliases instead of
  # all provider models.  (default: false)
  keep_only_aliases_at_models_endpoint: false

  # How configured provider model lists affect inventory:
  #   "fallback"    — env-discovered models supplement configured ones
  #   "allowlist"  — only explicitly configured models are available
  # (default: "fallback")
  configured_provider_models_mode: "fallback"

# ── Storage ─────────────────────────────────────────────────────────────
# Persistence for API keys, usage data, audit logs, and model overrides.
# SQLite works out of the box. Switch to PostgreSQL for production.
storage:
  # Backend type: "sqlite", "postgresql", or "mongodb"  (default: "sqlite")
  type: "sqlite"

  # SQLite settings (used when type = "sqlite")
  sqlite:
    path: "data/aurora.db"

  # PostgreSQL settings (used when type = "postgresql")
  # postgresql:
  #   url: "${POSTGRES_URL}"
  #   max_conns: 20

# ── Audit Logging ───────────────────────────────────────────────────────
# Records request/response metadata for auditing and debugging.
# WARNING: Enabling log_bodies may capture prompts, responses, and PII.
logging:
  enabled: true
  log_bodies: true
  log_headers: true
  only_model_interactions: true
  # buffer_size: 1000
  # flush_interval: 5
  # retention_days: 30

# ── Usage Tracking ──────────────────────────────────────────────────────
# Tracks token usage per request for billing, quotas, and analytics.
usage:
  enabled: true
  pricing_recalculation_enabled: true
  enforce_returning_usage_data: true
  # buffer_size: 1000
  # flush_interval: 5
  # retention_days: 90

# ── Prometheus Metrics ──────────────────────────────────────────────────
# Exposes Go runtime and application metrics for monitoring.
metrics:
  enabled: true
  endpoint: "/metrics"

# ── Guardrails ──────────────────────────────────────────────────────────
# Content safety filters applied to prompts and responses.
guardrails:
  enabled: true
  enable_for_batch_processing: false

# ── Caching ─────────────────────────────────────────────────────────────
# Three caching layers: model metadata, exact response, and semantic.
cache:
  # Model registry cache — reduces API calls to the model list URL.
  model:
    refresh_interval: 3600
    model_list:
      url: "https://raw.githubusercontent.com/aurorallm/aurora/refs/heads/main/docs-assets/assets/models.json"
      local_path: "data/models.local.json"
      user_overrides_path: "data/user_pricing.yaml"
    local:
      cache_dir: ".cache"
    # Redis-backed model cache (requires REDIS_URL env var to be set).
    # Falls back to the local file cache when Redis is unavailable.
    # redis:
    #   url: "${REDIS_URL}"
    #   key: "aurora:models"
    #   ttl: 86400

  # Response cache — stores LLM responses for reuse.
  # Two modes: simple (exact match) and semantic (similarity-based).
  # Both require Redis (for simple) and a vector store (for semantic).
  #
  # ── Simple (exact match) response cache ──
  # Returns cached response when the exact same prompt is sent again.
  # Only matches identical inputs; good for frequent, deterministic queries.
  #
  # ── Semantic (similarity) response cache ──
  # Embeds prompts and returns cached responses for semantically similar
  # inputs. Supports Qdrant, pgvector, Pinecone, and Weaviate backends.
  # Useful for repetitive but non-identical queries (e.g., customer support).
  #
  # Uncomment both sections below and set REDIS_URL + vector store vars.
  # response:
  #   simple:
  #     enabled: true
  #     redis:
  #       url: "${REDIS_URL}"
  #       key: "aurora:response:"
  #       ttl: 3600
  #   semantic:
  #     enabled: true
  #     similarity_threshold: 0.92
  #     prompt_similarity_threshold: 0.72
  #     ttl: 3600
  #     max_conversation_messages: 3
  #     exclude_system_prompt: false
  #     embedder:
  #       provider: "${SEMANTIC_CACHE_EMBEDDER_PROVIDER}"
  #       model: "${SEMANTIC_CACHE_EMBEDDER_MODEL}"
  #     vector_store:
  #       type: qdrant
  #       qdrant:
  #         url: "${SEMANTIC_CACHE_QDRANT_URL}"
  #         collection: "aurora_semantic"
  #       # type: pgvector
  #       # pgvector:
  #       #   url: "${SEMANTIC_CACHE_PGVECTOR_URL}"
  #       #   table: "aurora_semantic_cache"
  #       #   dimension: 1536
  #       # type: pinecone
  #       # pinecone:
  #       #   host: "${SEMANTIC_CACHE_PINECONE_HOST}"
  #       #   api_key: "${SEMANTIC_CACHE_PINECONE_API_KEY}"
  #       #   namespace: "${SEMANTIC_CACHE_PINECONE_NAMESPACE}"
  #       #   dimension: 1536
  #       # type: weaviate
  #       # weaviate:
  #       #   url: "${SEMANTIC_CACHE_WEAVIATE_URL}"
  #       #   class: "AuroraSemanticCache"
  #       #   api_key: "${SEMANTIC_CACHE_WEAVIATE_API_KEY}"

# ── Combo Models ────────────────────────────────────────────────────────
# Combo calls send the same request to multiple models and let you compare
# or aggregate responses. Useful for A/B testing, ensemble reasoning, etc.
combos:
  enabled: true
  # definitions:
  #   - name: "my-combo"
  #     enabled: true
  #     models:
  #       - "gpt-4o-mini"
  #       - "claude-sonnet-4"

# ── CLI Tools ───────────────────────────────────────────────────────────
# Allows admin users to apply configuration changes via CLI commands
# through the API. Disable in production unless needed.
cli_tools:
  enabled: true
  apply_enabled: false

# ── Token Saver ─────────────────────────────────────────────────────────
# HOW IT WORKS: Prepends a system message telling the model to answer
# concisely. Output-only - no input/tool-output compression.
#
# TO ACTIVATE: BOTH enabled AND output.enabled must be true.
#
# LEVELS (output.level): lite (concise), full (caveman), ultra (abbreviated),
# wenyan (classical Chinese).
token_saver:
  enabled: true
  endpoints: ["chat_completions"]
  apply_streaming: true
  output:
    enabled: true
    profile: "concise"
    level: "full"
  on_error: "allow"
  emit_headers: true
  audit:
    enabled: true

# ── Fallback Routing ────────────────────────────────────────────────────
# When the primary provider/model is unavailable, fallback defines what
# happens next:
#   auto   — automatically try alternative providers
#   manual — use a hand-written rules JSON file
#   off    — return error immediately
# Rules file lets you map a failed provider+model pair to a backup.
fallback:
  default_mode: "manual"
  manual_rules_path: "configs/fallback.json"

# ── Resilience ──────────────────────────────────────────────────────────
# Retry transient failures and stop calling repeatedly failing providers.
# All settings have sensible defaults — change only if you know why.
resilience:
  retry:
    max_retries: 3
    initial_backoff: 1s
    max_backoff: 30s
    backoff_factor: 2.0
    jitter_factor: 0.1
  circuit_breaker:
    failure_threshold: 5
    success_threshold: 2
    timeout: 30s

# ── Provider Configs ────────────────────────────────────────────────────
# Providers can be discovered automatically from env vars alone
# (e.g., setting OPENAI_API_KEY adds an "openai" provider). The explicit
# definitions below let you pin specific models, set custom base URLs,
# or scope API keys per provider instance.
#
# To configure multiple instances of the same provider, use a suffix:
#   OPENAI_EAST_API_KEY, OPENAI_EAST_BASE_URL, OPENAI_EAST_MODELS
#
# To use a custom provider, set type to an existing provider type and
# provide your own base_url + api_key.
#
# Uncomment providers you want to configure explicitly. Env-var auto-discovery
# works without this section — add definitions here only to pin models or
# override base URLs. Multiple instances: OPENAI_EAST_API_KEY → openai-east.
#
# providers:
#   # Custom / proxy provider:
#   # openai-proxy:
#   #   type: "openai"
#   #   api_key: "${OPENAI_PROXY_API_KEY}"
#   #   base_url: "${OPENAI_PROXY_BASE_URL}"
#   # openai:
#   #   type: "openai"
#   #   api_key: "${OPENAI_API_KEY}"
#   #   models:
#   #     - gpt-4o
#   #     - gpt-4o-mini
#   # anthropic:
#   #   type: "anthropic"
#   #   api_key: "${ANTHROPIC_API_KEY}"
#   # groq:
#   #   type: "groq"
#   #   api_key: "${GROQ_API_KEY}"
#   # gemini:
#   #   type: "gemini"
#   #   api_key: "${GEMINI_API_KEY}"
#   # openrouter:
#   #   type: "openrouter"
#   #   api_key: "${OPENROUTER_API_KEY}"
#   # deepseek:
#   #   type: "deepseek"
#   #   api_key: "${DEEPSEEK_API_KEY}"
#   # zai:
#   #   type: "zai"
#   #   api_key: "${ZAI_API_KEY}"
#   # xai:
#   #   type: "xai"
#   #   api_key: "${XAI_API_KEY}"
#   # minimax:
#   #   type: "minimax"
#   #   api_key: "${MINIMAX_API_KEY}"
#   # azure:
#   #   type: "azure"
#   #   api_key: "${AZURE_API_KEY}"
#   #   base_url: "${AZURE_BASE_URL}"
#   #   api_version: "2024-10-21"
#   # ollama:
#   #   type: "ollama"
#   #   base_url: "${OLLAMA_BASE_URL}"
#   # vllm:
#   #   type: "vllm"
#   #   base_url: "${VLLM_BASE_URL}"
#   # oracle:
#   #   type: "oracle"
#   #   api_key: "${ORACLE_API_KEY}"
#   #   base_url: "${ORACLE_BASE_URL}"

# ── Provider Pools ──────────────────────────────────────────────────────
# Groups multiple provider instances into a load-balanced pool.
# Supports strategies: "adaptive" (health-aware), "round_robin", "latency".
# Pools require multiple instances of the same provider type (e.g., two
# OpenAI instances configured via OPENAI_EAST_* and OPENAI_WEST_* env vars).
#
# pools:
#   my-pool:
#     members: ["openai-east", "openai-west"]
#     strategy: "adaptive"
#     health_aware: true

# ── Workflows ───────────────────────────────────────────────────────────
# How often to reload workflow definitions from storage.
workflows:
  refresh_interval: 1m
`

const initFallbackStub = `{
  "gpt-4o": [
    "groq/llama-3.3-70b-versatile",
    "gemini/gemini-2.5-flash"
  ],
  "claude-sonnet-4": [
    "openai/gpt-4o-mini"
  ]
}
`

const initPricingStub = `# User pricing/model overrides for Aurora Gateway
# Generated by aurora init
# Uncomment and customize model pricing as needed.
# See https://github.com/aurorallm/aurora for full reference.
#
# example:
# model_overrides:
#   openai/gpt-4o:
#     pricing:
#       input_per_mtok: 2.50
#       output_per_mtok: 10.00
`

const initEnvTemplate = `# ═══════════════════════════════════════════════════════════════════════════
# Aurora Gateway — Environment Variables
# Generated by aurora init
# ═══════════════════════════════════════════════════════════════════════════
#
# KEEP THIS FILE SECRET — it contains API keys, database URLs, and the
# gateway master key. Never commit it to version control.
#
# Config pipeline:  code defaults -> YAML config -> env vars (env vars win).
# Uncomment a variable and set its value to override the YAML or default.
#
# Available feature categories (all optional except the master key):
#   Provider API keys     Connect to LLM providers (OpenAI, Anthropic, etc.)
#   Server & Routing      Port, base path, Swagger, passthrough routes
#   Config & Overrides    Config file path, fallback routing mode
#   Storage               SQLite (default), PostgreSQL, or MongoDB
#   Admin & Metrics       Admin dashboard + Prometheus metrics
#   Audit Logging         Log requests/responses for auditing
#   Usage Tracking        Token usage count, pricing, and retention
#   Guardrails            Content safety filters
#   Model Registry        Model discovery URL, local snapshots, overrides
#   Redis Cache           Model metadata cache + exact response cache
#   Semantic Cache        Embedding-based similarity cache (Qdrant/pgvector)
#   Token Saver           Output compression / token-saving transforms
#   Resilience            Retry logic and circuit breaker
#   Logging & Metadata    Log format, level, service name
#   HTTP Client           Upstream timeouts and proxy
#   Combos & CLI Tools    Combo model calls, admin CLI integration
#   Workflows             Workflow definition refresh rate
# ═══════════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════════
#  REQUIRED — you MUST set these
# ═══════════════════════════════════════════════════════════════════════════

# Gateway master key. Protects the admin API, dashboard, and all routes.
# Set to a long, random string. CHANGE THIS before exposing outside localhost.
AURORA_MASTER_KEY=master-key

# ═══════════════════════════════════════════════════════════════════════════
#  LLM PROVIDERS — uncomment at least one to connect to an AI provider
# ═══════════════════════════════════════════════════════════════════════════
#
# Each provider can also define a base URL and/or model list.
# Multiple instances of the same provider: use suffixes separated by
# underscores (e.g. OPENAI_EAST_API_KEY, OPENAI_WEST_API_KEY).

# ── OpenAI ──────────────────────────────────────────────────────────────
# # API key from platform.openai.com/api-keys
# OPENAI_API_KEY=sk-proj-...
# # Base URL for OpenAI-compatible API (change for proxies)
# OPENAI_BASE_URL=https://api.openai.com/v1
# # Comma-separated model IDs to restrict this provider to
# OPENAI_MODELS=gpt-4o,gpt-4o-mini

# ── Anthropic Claude ────────────────────────────────────────────────────
# # API key from console.anthropic.com
# ANTHROPIC_API_KEY=sk-ant-...
# ANTHROPIC_BASE_URL=https://api.anthropic.com/v1
# # Default max tokens for Anthropic requests
# ANTHROPIC_DEFAULT_MAX_TOKENS=4096
# ANTHROPIC_MODELS=claude-sonnet-4-20250514,claude-opus-4-20250514

# ── Google Gemini ───────────────────────────────────────────────────────
# # API key from aistudio.google.com/apikey
# GEMINI_API_KEY=...
# GEMINI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai
# GEMINI_MODELS=gemini-2.5-pro,gemini-2.5-flash

# ── Groq ────────────────────────────────────────────────────────────────
# # API key from console.groq.com/keys
# GROQ_API_KEY=gsk_...
# GROQ_BASE_URL=https://api.groq.com/openai/v1
# GROQ_MODELS=llama-3.3-70b-versatile,deepseek-r1-distill-llama-70b

# ── DeepSeek ────────────────────────────────────────────────────────────
# DEEPSEEK_API_KEY=...
# DEEPSEEK_BASE_URL=https://api.deepseek.com
# DEEPSEEK_MODELS=deepseek-chat,deepseek-reasoner

# ── OpenRouter ──────────────────────────────────────────────────────────
# # API key from openrouter.ai/keys
# OPENROUTER_API_KEY=sk-or-...
# OPENROUTER_BASE_URL=https://openrouter.ai/api/v1
# # Recommended: identify your app for OpenRouter analytics
# OPENROUTER_SITE_URL=https://github.com/your-project
# OPENROUTER_APP_NAME=MyApp
# OPENROUTER_MODELS=openai/gpt-4o,anthropic/claude-sonnet-4

# ── Z.ai ────────────────────────────────────────────────────────────────
# ZAI_API_KEY=...
# ZAI_BASE_URL=https://api.z.ai/api/paas/v4
# ZAI_MODELS=glm-4.5

# ── xAI (Grok) ──────────────────────────────────────────────────────────
# XAI_API_KEY=...
# XAI_BASE_URL=https://api.x.ai/v1
# XAI_MODELS=grok-3,grok-3-mini

# ── MiniMax ─────────────────────────────────────────────────────────────
# MINIMAX_API_KEY=...
# MINIMAX_BASE_URL=https://api.minimax.io/v1
# MINIMAX_MODELS=minimax-m1

# ── Azure OpenAI ────────────────────────────────────────────────────────
# AZURE_API_KEY=...
# AZURE_BASE_URL=https://your-resource.openai.azure.com/
# AZURE_API_VERSION=2024-10-21
# AZURE_MODELS=gpt-4o

# ── Oracle OCI Generative AI ────────────────────────────────────────────
# ORACLE_API_KEY=...
# ORACLE_BASE_URL=https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/v1
# ORACLE_MODELS=cohere.command-r-plus

# ── Ollama (local) ──────────────────────────────────────────────────────
# OLLAMA_API_KEY=
# OLLAMA_BASE_URL=http://localhost:11434/v1
# OLLAMA_MODELS=llama3.1,mistral

# ── vLLM (local) ────────────────────────────────────────────────────────
# VLLM_API_KEY=
# VLLM_BASE_URL=http://localhost:8000/v1
# VLLM_MODELS=local-model

# ── Custom / Proxy Providers ───────────────────────────────────────────
# You can define any provider by suffixing env vars with an instance name.
# Underscores in the suffix become hyphens in the provider name.
# Examples (uncomment one and replace values):
# OPENAI_PROXY_API_KEY=replace-with-key
# OPENAI_PROXY_BASE_URL=https://proxy.example.com/openai/v1
# OPENAI_PROXY_MODELS=gpt-4o-mini
# GOOGLE_PROXY_API_KEY=replace-with-key
# GOOGLE_PROXY_BASE_URL=https://proxy.example.com/google/v1beta
# GOOGLE_PROXY_MODELS=gemini-2.5-flash
# JINA_API_KEY=replace-with-key
# JINA_BASE_URL=https://api.jina.ai/v1
# JINA_MODELS=jina-embeddings-v3

# ═══════════════════════════════════════════════════════════════════════════
#  SERVER & ROUTING — HTTP server and endpoint configuration
# ═══════════════════════════════════════════════════════════════════════════
# PORT=8080                                         # HTTP listen port
# BASE_PATH=/                                       # URL prefix when behind a reverse proxy
# BODY_SIZE_LIMIT=10M                               # Max request body (e.g. 10M, 1G, 500K)
SWAGGER_ENABLED=true                                # Expose Swagger UI at /swagger/index.html
PPROF_ENABLED=true                                  # Expose Go pprof at /debug/pprof/*
# ENABLE_PASSTHROUGH_ROUTES=true                    # Enable /p/{provider}/... pass-through routes
# ALLOW_PASSTHROUGH_V1_ALIAS=true                   # Allow /p/{provider}/v1/... alias URLs
# ENABLED_PASSTHROUGH_PROVIDERS=openai,anthropic    # Providers with passthrough routes
ENABLE_ANTHROPIC_INGRESS=true                       # Expose /v1/messages (Anthropic format)
# DISABLE_REQUEST_LOGGING=false                     # Disable Echo built-in request logger
# DISABLE_REQUEST_BODY_SNAPSHOT=false               # Skip eager request body capture
# DISABLE_PASSTHROUGH_SEMANTIC_ENRICHMENT=false     # Skip provider metadata enrichment

# ═══════════════════════════════════════════════════════════════════════════
#  CONFIG & DASHBOARD OVERRIDES
# ═══════════════════════════════════════════════════════════════════════════
# Point to a custom config file (default: configs/config.yaml, fallback: config.yaml)
# AURORA_CONFIG_PATH=configs/editions/oss.example.yaml
# Default fallback mode when a provider is unavailable: auto, manual, or off
# FEATURE_FALLBACK_MODE=manual
# Path to JSON file with manual fallback routing rules
# FALLBACK_MANUAL_RULES_PATH=./fallback.local.json
# How often to refresh workflow definitions from storage (Go duration)
# WORKFLOW_REFRESH_INTERVAL=1m

# ═══════════════════════════════════════════════════════════════════════════
#  STORAGE — database backend for persistence
# ═══════════════════════════════════════════════════════════════════════════
# Backend type: sqlite (default), postgresql, or mongodb
STORAGE_TYPE=sqlite
SQLITE_PATH=data/aurora.db
# PostgreSQL (switch STORAGE_TYPE=postgresql and set the URL)
# POSTGRES_URL=postgres://user:pass@localhost:5432/aurora?sslmode=disable
# POSTGRES_MAX_CONNS=10
# MongoDB (switch STORAGE_TYPE=mongodb and set the URL)
# MONGODB_URL=mongodb://localhost:27017/aurora

# ═══════════════════════════════════════════════════════════════════════════
#  ADMIN API & METRICS
# ═══════════════════════════════════════════════════════════════════════════
ADMIN_ENDPOINTS_ENABLED=true                         # Admin REST API at /admin/api/v1/*
ADMIN_UI_ENABLED=true                                # Admin web dashboard at /admin/dashboard

METRICS_ENABLED=true                                 # Prometheus metrics at /metrics
METRICS_ENDPOINT=/metrics

# ═══════════════════════════════════════════════════════════════════════════
#  AUDIT LOGGING — records request/response metadata
# ═══════════════════════════════════════════════════════════════════════════
LOGGING_ENABLED=true                                 # Enable audit logging
# ⚠ WARNING: Enabling LOGGING_LOG_BODIES captures prompts, responses, and PII
LOGGING_LOG_BODIES=false
LOGGING_LOG_HEADERS=false
LOGGING_ONLY_MODEL_INTERACTIONS=true                 # Skip /health, /metrics, /admin
LOGGING_BUFFER_SIZE=1000                             # In-memory queue capacity
LOGGING_FLUSH_INTERVAL=5                             # Flush to storage every N seconds
LOGGING_RETENTION_DAYS=30                            # Auto-delete after N days (0 = forever)

# ═══════════════════════════════════════════════════════════════════════════
#  USAGE TRACKING — token counts and pricing data
# ═══════════════════════════════════════════════════════════════════════════
USAGE_ENABLED=true                                   # Track token usage
USAGE_PRICING_RECALCULATION_ENABLED=true             # Admin can recalculate costs
ENFORCE_RETURNING_USAGE_DATA=true                    # Add include_usage to streaming requests
USAGE_BUFFER_SIZE=1000                               # In-memory usage queue capacity
USAGE_FLUSH_INTERVAL=5                               # Flush every N seconds
USAGE_RETENTION_DAYS=90                              # Auto-delete older than N days (0 = forever)

# ═══════════════════════════════════════════════════════════════════════════
#  GUARDRAILS — content safety filters
# ═══════════════════════════════════════════════════════════════════════════
GUARDRAILS_ENABLED=true                              # Apply configured guardrails globally
ENABLE_GUARDRAILS_FOR_BATCH_PROCESSING=false          # Also apply to batch job items

# ═══════════════════════════════════════════════════════════════════════════
#  MODEL REGISTRY & ACCESS CONTROL
# ═══════════════════════════════════════════════════════════════════════════
MODEL_LIST_URL=https://raw.githubusercontent.com/aurorallm/aurora/refs/heads/main/docs-assets/assets/models.json # Upstream model metadata URL
MODEL_LIST_LOCAL_PATH=data/models.local.json                    # Local snapshot path
MODEL_LIST_USER_OVERRIDES_PATH=data/user_pricing.yaml           # Pricing overrides YAML
MODELS_ENABLED_BY_DEFAULT=true                              # Default model availability
MODEL_OVERRIDES_ENABLED=true                                # Allow per-model overrides
KEEP_ONLY_ALIASES_AT_MODELS_ENDPOINT=false                  # Show only aliases at /v1/models
CONFIGURED_PROVIDER_MODELS_MODE=fallback                     # "fallback" or "allowlist"
CACHE_REFRESH_INTERVAL=3600                                  # Model cache refresh (seconds)
AURORA_CACHE_DIR=.cache                                      # Local cache directory

# ═══════════════════════════════════════════════════════════════════════════
#  REDIS CACHE — model metadata + exact response cache
# ═══════════════════════════════════════════════════════════════════════════
# Set REDIS_URL to enable Redis. Used for model cache and/or response cache.
# REDIS_URL=redis://localhost:6379
# Model cache (speeds up model registry lookups)
# REDIS_KEY_MODELS=aurora:models
# REDIS_TTL_MODELS=86400
# Simple exact-match response cache (caches full LLM responses)
# RESPONSE_CACHE_SIMPLE_ENABLED=false
# REDIS_KEY_RESPONSES=aurora:response:
# REDIS_TTL_RESPONSES=3600

# ═══════════════════════════════════════════════════════════════════════════
#  SEMANTIC CACHE — embedding-based similarity cache
# ═══════════════════════════════════════════════════════════════════════════
# Stores prompt embeddings and returns cached responses when a new prompt
# is semantically similar (above the threshold). Supports multiple vector
# store backends: Qdrant (default), pgvector, Pinecone, Weaviate.
#
# SEMANTIC_CACHE_ENABLED=false
# Similarity threshold (0-1). Higher = stricter match.  (default: 0.92)
# SEMANTIC_CACHE_THRESHOLD=0.92
# Prompt-only similarity threshold for the prompt embedding  (default: 0.72)
# SEMANTIC_CACHE_PROMPT_SIMILARITY=0.72
# Cache entry TTL in seconds  (default: 3600)
# SEMANTIC_CACHE_TTL=3600
# Recent messages to include in cache key  (default: 3)
# SEMANTIC_CACHE_MAX_CONV_MESSAGES=3
# Exclude system prompt from cache keys  (default: false)
# SEMANTIC_CACHE_EXCLUDE_SYSTEM_PROMPT=false
#
# Embedder configuration
# SEMANTIC_CACHE_EMBEDDER_PROVIDER=openai
# SEMANTIC_CACHE_EMBEDDER_MODEL=text-embedding-3-small
#
# Vector store backend: qdrant, pgvector, pinecone, or weaviate
# SEMANTIC_CACHE_VECTOR_STORE_TYPE=qdrant
#
# ── Qdrant ────────────────────────────────────────────────────────────
# SEMANTIC_CACHE_QDRANT_URL=http://localhost:6333
# SEMANTIC_CACHE_QDRANT_COLLECTION=aurora_semantic
# SEMANTIC_CACHE_QDRANT_API_KEY=
#
# ── pgvector ──────────────────────────────────────────────────────────
# SEMANTIC_CACHE_PGVECTOR_URL=postgres://user:pass@localhost:5432/aurora
# SEMANTIC_CACHE_PGVECTOR_TABLE=aurora_semantic_cache
# SEMANTIC_CACHE_PGVECTOR_DIMENSION=1536
#
# ── Pinecone ──────────────────────────────────────────────────────────
# SEMANTIC_CACHE_PINECONE_HOST=https://your-index.svc.region.pinecone.io
# SEMANTIC_CACHE_PINECONE_API_KEY=
# SEMANTIC_CACHE_PINECONE_NAMESPACE=
# SEMANTIC_CACHE_PINECONE_DIMENSION=1536
#
# ── Weaviate ──────────────────────────────────────────────────────────
# SEMANTIC_CACHE_WEAVIATE_URL=http://localhost:8080
# SEMANTIC_CACHE_WEAVIATE_CLASS=AuroraSemanticCache
# SEMANTIC_CACHE_WEAVIATE_API_KEY=

# ═══════════════════════════════════════════════════════════════════════════
#  TOKEN SAVER — output-only system-prompt injection
# ═══════════════════════════════════════════════════════════════════════════
# Prepends a system message telling the model to be terse. BOTH
# TOKEN_SAVER_ENABLED=true AND TOKEN_SAVER_OUTPUT_ENABLED=true must be set.
# Levels: lite (concise), full (caveman), ultra (abbreviated), wenyan (文言文).
#
TOKEN_SAVER_ENABLED=true
# TOKEN_SAVER_ENDPOINTS=chat_completions
# TOKEN_SAVER_APPLY_STREAMING=true
# TOKEN_SAVER_OUTPUT_ENABLED=false    # set true to activate injection
# TOKEN_SAVER_OUTPUT_PROFILE=concise
# TOKEN_SAVER_OUTPUT_LEVEL=full       # lite, full, ultra, wenyan
# TOKEN_SAVER_MODELS_INCLUDE=
# TOKEN_SAVER_MODELS_EXCLUDE=
# TOKEN_SAVER_PROVIDERS_INCLUDE=
# TOKEN_SAVER_PROVIDERS_EXCLUDE=
# TOKEN_SAVER_ON_ERROR=allow
# TOKEN_SAVER_EMIT_HEADERS=true
# TOKEN_SAVER_AUDIT_ENABLED=true

# ═══════════════════════════════════════════════════════════════════════════
#  RESILIENCE — retry logic and circuit breaker
# ═══════════════════════════════════════════════════════════════════════════
# Retry settings for upstream provider calls
# RETRY_MAX_RETRIES=3
# RETRY_INITIAL_BACKOFF=1s
# RETRY_MAX_BACKOFF=30s
# RETRY_BACKOFF_FACTOR=2.0
# RETRY_JITTER_FACTOR=0.1
#
# Circuit breaker — stops calling a failing provider temporarily
# CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
# CIRCUIT_BREAKER_SUCCESS_THRESHOLD=2
# CIRCUIT_BREAKER_TIMEOUT=30s

# ═══════════════════════════════════════════════════════════════════════════
#  LOGGING & RUNTIME METADATA
# ═══════════════════════════════════════════════════════════════════════════
# Log format: "json" for structured JSON, "text" for human-readable
# LOG_FORMAT=text
# Log level: debug, info, warn, error  (default: info)
# LOG_LEVEL=info
# Include source file/line in log messages
# LOG_ADD_SOURCE=false
# Custom service name for structured log output
# SERVICE_NAME=aurora-gateway
# Deployment environment label
# ENV=development

# ═══════════════════════════════════════════════════════════════════════════
#  HTTP CLIENT — upstream request timeouts and proxy
# ═══════════════════════════════════════════════════════════════════════════
# Overall upstream request timeout in seconds  (default: 600)
# HTTP_TIMEOUT=600
# Time to wait for upstream response headers in seconds  (default: 600)
# HTTP_RESPONSE_HEADER_TIMEOUT=600
# HTTP/HTTPS proxy for outbound requests to LLM providers
# HTTP_PROXY=http://proxy:8080
# HTTPS_PROXY=http://proxy:8080
# Comma-separated hosts to bypass the proxy
# NO_PROXY=localhost,127.0.0.1

# ═══════════════════════════════════════════════════════════════════════════
#  COMBOS & CLI TOOLS
# ═══════════════════════════════════════════════════════════════════════════
# Enable combo model calls (send same request to multiple models)
# COMBOS_ENABLED=true
# Enable CLI tools integration through the API
# CLI_TOOLS_ENABLED=true
# Allow admin/API to apply CLI tool changes
# CLI_TOOLS_APPLY_ENABLED=false

`
